### PR TITLE
add support to use existing secret and replace glide with go modules

### LINKED ISSUE #26: Take Sensitive Information from Secrets
Right now ProxyInjector uses Client-secret directly as a string. It would  be a better and secure approach if it takes this sensitive information from Secrets

### PR DESCRIPTION
**Pull request by usamaahmadkhan**
Closes  #26 . 
- [x]  Support Secrets alongside configmap ( Fixed by #31 ) 
- [x]  Support existing secrets ( fixed by this PR )
- [x]  Move from glide to go modules

### CODE REVIEW

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. ``docker pull stakater/proxyinjector:SNAPSHOT-PR-33-1``

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater/job/ProxyInjector/job/PR-33/2/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater/job/ProxyInjector/job/PR-33/3/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. ``docker pull stakater/proxyinjector:SNAPSHOT-PR-33-4``

**Review by aliartiza75 — APPROVED** [review]

**Review by kahootali — APPROVED** [review]

**Pull request merged**
