### PR TITLE
Update api versions

### LINKED ISSUE #36: proxyinjector fails on kubernetes 1.16
When deploying on kubernetes 1.16 proxyinjector fails with:

``` reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to list *v1beta1.Deployment: the server could not find the requested resource```

This is due to the change in the api to `apiVersion: apps/v1`

### PR DESCRIPTION
**Pull request by m4ldonado**
Fixes #36

Kubectl apply works now - but I haven't tested it further than that.

`~/E/P/d/kubernetes> (master|✔) $ kubectl apply -f proxyinjector.yaml
serviceaccount/proxyinjector created
clusterrole.rbac.authorization.k8s.io/proxyinjector-role created
clusterrolebinding.rbac.authorization.k8s.io/proxyinjector-role-binding created
deployment.apps/proxyinjector created
deployment.apps/proxyinjector configured
serviceaccount/proxyinjector configured
clusterrole.rbac.authorization.k8s.io/proxyinjector-role configured
clusterrolebinding.rbac.authorization.k8s.io/proxyinjector-role-binding configured
configmap/proxyinjector created
`

### CODE REVIEW

**Comment by stakater-user** [comment]
@m4ldonado Image is available for testing. ``docker pull stakater/proxyinjector:SNAPSHOT-PR-37-1``

**Comment by m4ldonado** [comment]
I think I'll need to update the go.mod file as well

**Comment by m4ldonado** [comment]
thanks for supplying the image @rasheedamir!  I edited the yaml file to point to the new image and ran kubectl apply and kubectl logs no longer shows the error message from #36 .  I didn't touch the go.mod file so I'll leave that alone

**Review by usamaahmadkhan — APPROVED** [review]

**Comment by usamaahmadkhan** [comment]
@m4ldonado must be a typo. Reviewed. LGTM

**Pull request merged**
